### ISSUE TITLE
Typescript Migration - Runtime Error / Expected "payload" to be a plain object

### ISSUE THREAD

**Issue by app-generator** [app-generator/api-server-nodejs#7]
**Symptom**

During the `http://localhost:5000/api/users/login` request, the server bumps runtime error:

**Expected "payload" to be a plain object**

Full error log: 

```log
yarn dev  
yarn run v1.22.5
$ ts-node-dev src/index.ts
[INFO] 08:06:11 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.3.5)
Server is listening on port 5000
MongoDB Connected
Error: Expected "payload" to be a plain object.
    at validate (D:\work\repo-api-servers\api-server-nodejs\node_modules\jsonwebtoken\sign.js:40:11)
    at validatePayload (D:\work\repo-api-servers\api-server-nodejs\node_modules\jsonwebtoken\sign.js:62:10)
    at Object.module.exports [as sign] (D:\work\repo-api-servers\api-server-nodejs\node_modules\jsonwebtoken\sign.js:114:7)
    at D:\work\repo-api-servers\api-server-nodejs\src\routes\users.ts:90:27
    at D:\work\repo-api-servers\api-server-nodejs\node_modules\bcrypt-nodejs\bCrypt.js:689:3
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[ERROR] 08:06:22 Error: Expected "payload" to be a plain object.
```

**Expected behaviour** 

Have a successful login.

**Comment by app-generator** [comment]
Fixed in **v0.0.7**

Full information regarding the patch:
https://stackoverflow.com/questions/52781477/expected-payload-to-be-a-plain-object-mean
